### ISSUE TITLE
thread safe 

### ISSUE THREAD

**Issue by 1a1a11a** [cachelot/cachelot#24]
If I use it as standalone caching library, is it thread safe? And how does it compare with unordered_map?

**Comment by aka-rider** [comment]
Hi.

> If I use it as standalone caching library, is it thread safe?
No. It is not thread safe by design. I tried several approaches, including lock-free techniques, but overhead on synchronisation is just too big.

>And how does it compare with unordered_map?
Last time I checked, Cachelot was several times faster, assuming there are hundreds or thousands of items (if items are few, everything settle down in a CPU cache, and difference is not that significant)

It should be relatively easy to get exact numbers based on this benchmark: https://github.com/cachelot/cachelot/blob/master/src/benchmark/benchmark_cache.cpp


The more important that Cachelot doesn't allocate memory dynamically - it always works within pre-allocated slab.

Please also note that unlike unordered_map, Cachelot doesn't call constructors/destructors of the stored items, so it only works with POD types.

**Comment by 1a1a11a** [comment]
I see, thank you!

**Comment by aka-rider** [comment]
You're welcome. Do not hesitate to ask more questions.
