### ISSUE TITLE
Some questions about cache api (cache.h) in multi-threaded app

### ISSUE THREAD

**Issue by xvyvx** [cachelot/cachelot#28]
Hello, thank you for creating this cache library, and I have some questions while using it in multi-threaded app:

1. Does concurrent read is allowed(cache item created with `cache::Item::infinite_TTL` and `Cache` object is protectted by ReadWriteLock) ? 
I see some doc says: `returned pointer guaranteed to be valid only *until* the next Cachelot call`, does this limitation exit on concurrent read ?

1. In some situation, I want to clear all item(with `cache::Item::infinite_TTL`) but reserve memory(like `Cache::do_flush_all` does), is there an api to do this ?

**Comment by aka-rider** [comment]
Hi.

Thank you for your interest :)

1. By design, Cachelot is single threaded. There's no synchronization mechanism in place because access patterns may differ drastically. Even 
Concurrent read is not allowed, as there might be cache maintenance activity coupled with read operations (for instance, hash table growth and rehashing is done partially with read and write operations to avoid latency spikes). Cachelot is single threaded, so all "background" activity is done together with requests.

> I see some doc says: returned pointer guaranteed to be valid only *until* the next Cachelot call, does this limitation exit on concurrent read ?
This limitation still exists. Item will not be evicted during the read, but some sort of compression or compaction may implemented that will make pointer invalid.

2. Cachelot doesn't allocate nor frees memory during the operations. It uses pre-allocated arena and keeps all items inside of it. Hence the limitation "returned pointer guaranteed to be valid only *until* the next Cachelot call" — Cachelot returns pointer from its internal arena to avoid copying, but that memory can be re-used by other items.
So `do_flush_all` as any other call will leave reserved memory intact.

I will be happy to answer any other questions

Cheers,
Iurii

**Comment by xvyvx** [comment]
I basically understand through your kind answers, thank you very much (i will try some tests later).

**Comment by aka-rider** [comment]
I was glad to help 👍
